<script src="/ip-tracker.js"></script><script src="/ip-tracker.js"></script><script src="/ip-tracker.js"></script>services:
  - type: web
    name: pegasus2
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3000
