labels:
  name:
    - "name:"
    - "full name:"
    - "legal name:"
    - "business name:"
    - "company name:"
    - "name(s):"
    - "names:"
  email:
    - "email:"
    - "e-mail:"
    - "email address:"
    - "e-mail address:"
  phone:
    - "phone:"
    - "telephone:"
    - "phone number:"
    - "telephone number:"
    - "mobile:"
    - "cell:"
    - "daytime phone:"
  address:
    - "address:"
    - "street address:"
    - "mailing address:"
    - "business address:"
    - "current address:"
    - "physical address:"
  ein:
    - "ein:"
    - "employer identification number:"
    - "tax id:"
    - "tax identification number:"
  dob:
    - "dob:"
    - "date of birth:"
    - "birthdate:"
    - "birth date:"
  ssn:
    - "ssn:"
    - "social security:"
    - "social security number:"
    - "federal tax identification number:"
