fields:
  - key: name
    acroform_names:
      - "name"
      - "names"
      - "full_name"
      - "legal_name"
      - "business_name"
      - "company_name"
      - "organization_name"
      - "claimant_name"
      - "applicant_name"
      - "first_name"
      - "given_name"
      - "family_name"
      - "surname"
      - "owner_name"
      - "authorized_name"
      - "printed_name"
      - "signer_name"
      - "contact_name"
      - "primary_name"
      - "secondary_name"
      - "preferred_name"
    write:
      anchor_label: name
      offset:
        dx: 10
        dy: 0
      font_size: 10
  - key: email
    acroform_names:
      - "email"
      - "email_address"
      - "e_mail"
      - "e_mail_address"
    write:
      anchor_label: email
      offset:
        dx: 10
        dy: 0
      font_size: 10
  - key: phone
    acroform_names:
      - "phone"
      - "telephone"
      - "phone_number"
      - "mobile"
      - "cell"
      - "daytime_phone"
    write:
      anchor_label: phone
      offset:
        dx: 10
        dy: 0
      font_size: 10
  - key: address
    acroform_names:
      - "address"
      - "street_address"
      - "mailing_address"
      - "business_address"
      - "current_address"
    write:
      anchor_label: address
      offset:
        dx: 10
        dy: 0
      font_size: 10
  - key: ein
    acroform_names:
      - "ein"
      - "employer_identification_number"
      - "tax_id"
      - "tax_identification_number"
    write:
      anchor_label: ein
      offset:
        dx: 10
        dy: 0
      font_size: 10
  - key: dob
    acroform_names:
      - "dob"
      - "date_of_birth"
      - "birthdate"
      - "birth_date"
    write:
      anchor_label: dob
      offset:
        dx: 10
        dy: 0
      font_size: 10
  - key: ssn
    acroform_names:
      - "ssn"
      - "social_security"
      - "social_security_number"
      - "federal_tax_identification_number"
    write:
      anchor_label: ssn
      offset:
        dx: 10
        dy: 0
      font_size: 10
