name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint
        run: |
          flake8 app --max-line-length=120

      - name: Smoke test (import processor)
        run: |
          python - << 'PY'
          import importlib.util, sys, pathlib
          p = pathlib.Path('app/processor.py')
          spec = importlib.util.spec_from_file_location("processor", p)
          mod = importlib.util.module_from_spec(spec)
          spec.loader.exec_module(mod)
          print("Processor import OK")
          PY
